baseURL = "http://lucid-gates-dcfaea.netlify.com/"
languageCode = "en-us"
title = "Jacob Mziya"
theme = "hugo-initio"
publishDir = "public"

[params]
    name = "Jacob Mziya"
    description = "Web Developer | Writer | Social Media Marketer"
    email = "jacobmziya@gmail.com"
    phone = "+265 999 478 629"
    address = "Area 15, Lilongwe, Malawi, Africa"
    year = 2018
    background = ""
    favicon = "images/gt_favicon.png"
    DateForm = "January 1, 2006"

    showSubheader = true
    showServices = true
    showRecentWorks = true
    showDownload = false
    showClients = false

    footerEnableContact = true
    footerEnableFollowme = true
    footerEnableTextWidget = false
    footerEnableFormWidget = false

[[menu.main]]
    name = "home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Personal Development"
    url = "/personal_development/"
    weight = 3

[params.disqus]
    site = ""

[params.sharethis]
    property = "123456789012345678901234"
    custom = true

[params.google.analytics]
    trackerID = "UA-116833696-2"

[[params.social]]
	title = "facebook"
	url = "https://www.facebook.com/jmziya"
    icon = "fa-facebook-square"
    footer = true
    sharethis = true
    network = "facebook"
[[params.social]]
	title = "twitter"
	url = "https://twitter.com/JacobNow_Izrael"
    icon = "fa-twitter-square"
    footer = true
    sharethis = true
    network = "twitter"
[[params.social]]
	title = "instagram"
	url = "https://www.instagram.com/jacobmziya"
    icon = "fa-instagram"
    footer = true
    sharethis = false
    network = ""
[[params.social]]
	title = "google+"
	url = "https://plus.google.com/+JacobMziyaGP"
    icon = "fa-google-plus-square"
    footer = false
    sharethis = true
    network = "googleplus"
[[params.social]]
	title = "linkedin"
	url = ""
    icon = "fa-linkedin-square"
    footer = false
    sharethis = true
    network = "linkedin"
[[params.social]]
	title = "tumblr"
	url = ""
    icon = "fa-tumblr-square"
    footer = false
    sharethis = false
    network = "tumblr"
[[params.social]]
	title = "github"
	url = "https://github.com/jmziya"
    icon = "fa-github"
    footer = true
    sharethis = false
    network = ""
[[params.social]]
	title = "email"
	url = "mailto:jacobmziya@gmail.com"
    icon = "fa-envelope"
    footer = false
    sharethis = true
network = "email"
